CREATE TABLE [MDV401_MotivoRechazos] (
    [RYEMP] NUMERIC(2),
    [RYCOST] NUMERIC(2),
    [RYAGEN] NUMERIC(2),
    [RYCODMOT] NUMERIC(4),
    [RYDESCMOT] NVARCHAR(45),
    [RYFECH] NUMERIC(8),
    [RYHORA] BIGINT,
    [RYUSER] NVARCHAR(10)
)