CREATE TABLE [MDV402_Rechazo_Cab] (
    [RXEMP] NUMERIC(2),
    [RXCOST] NUMERIC(2),
    [RXAGEN] NUMERIC(2),
    [RXNRRECH] NUMERIC(10),
    [RXNRPED] NUMERIC(6),
    [RXFECHAP] DATETIME,
    [RXCONCR] NVARCHAR(1),
    [RXNRCLI] NUMERIC(6),
    [RXNRVEN] NUMERIC(6),
    [RXCODDIS] NUMERIC(6),
    [RXCODMOT] NUMERIC(4),
    [RXFECH] NUMERIC(8),
    [RXHORA] BIGINT,
    [RXUSER] NVARCHAR(10)
)