CREATE TABLE [MDV403_Rechazo_Det] (
    [RZEMP] NUMERIC(2),
    [RZCOST] NUMERIC(2),
    [RZAGEN] NUMERIC(2),
    [RZNRRECH] NUMERIC(10),
    [RZARTI] NUMERIC(3),
    [RZTIPR] NUMERIC(2),
    [RZSABOR] NUMERIC(2),
    [RZCTD] NUMERIC(7)
)