CREATE TABLE [MDV636_ObjetivosVenta] (
    [O1EMP] NUMERIC(2),
    [O1COST] NUMERIC(2),
    [O1AGEN] NUMERIC(2),
    [O1GEST] NUMERIC(4),
    [O1GRUP] NUMERIC(2),
    [O1DIST] NUMERIC(3),
    [O1RUTA] NUMERIC(4),
    [O1MES] NUMERIC(2),
    [O1OBJD] NUMERIC(8),
    [O1OBJA] NUMERIC(8),
    [O1FECH] NUMERIC(8),
    [O1HORA] BIGINT,
    [O1USER] NVARCHAR(10)
)