ALTER TABLE [dbo].[MDV004_Pedidos_det] ALTER COLUMN [P1EMP] numeric(2,0) NOT NULL
GO
ALTER TABLE [dbo].[MDV004_Pedidos_det] ALTER COLUMN [P1COST] numeric(2,0) NOT NULL
GO
ALTER TABLE [dbo].[MDV004_Pedidos_det] ALTER COLUMN [P1AGEN] numeric(2,0) NOT NULL
GO
ALTER TABLE [dbo].[MDV004_Pedidos_det] ALTER COLUMN [P1NRPE] numeric(6,0) NOT NULL
GO
ALTER TABLE [dbo].[MDV004_Pedidos_det] ALTER COLUMN [P1ARTI] numeric(3,0) NOT NULL
GO
ALTER TABLE [dbo].[MDV004_Pedidos_det] ALTER COLUMN [P1TIPR] numeric(2,0) NOT NULL
GO
ALTER TABLE [dbo].[MDV004_Pedidos_det] ALTER COLUMN [P1SABOR] numeric(2,0) NOT NULL
GO
ALTER TABLE [dbo].[MDV004_Pedidos_det]
	ADD CONSTRAINT [pk_detPedidos]
	PRIMARY KEY ([P1EMP], [P1COST], [P1AGEN], [P1NRPE], [P1ARTI], [P1TIPR], [P1SABOR])
GO
